version: 2.1
apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt update
    sudo apt install -y graphviz build-essential libopenjp2-7 python3-dev pandoc
tox: &tox
  name: Setup tox
  command: |
    python -m pip install --upgrade tox
jobs:
  website:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: *apt-install
      - run: *tox
      - run: python -m tox -e website
      - store_artifacts:
          path: .tmp/website/sunpy.org/_build/html
  sunpy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: *apt-install
      - run: *tox
      - run: python -m tox -e sunpy-docs
      - store_artifacts:
          path: .tmp/sunpy-docs/sunpy/docs/_build/html
  test_package:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: *apt-install
      - run: *tox
      - run: python -m tox -e testpackage-docs
      - store_artifacts:
          path: test_package/docs/_build/html
  css_linting:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: sudo npm install -g stylelint
      - run: sudo npm install stylelint-config-recommended
      - run: sudo stylelint "**/*.{css,scss,sass}"
workflows:
  version: 2
  tests:
    jobs:
      - css_linting
      - sunpy
      - test_package
      - website
notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
