version: 2.1
apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt update
    sudo apt install -y graphviz build-essential libopenjp2-7 python3-dev pandoc libcairo2-dev
tox: &tox
  name: Setup tox
  command: |
    python -m pip install --upgrade tox
jobs:
  website:
    resource_class: large
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: *apt-install
      - run: *tox
      - run: python -m tox -e website -- -j 8
      - store_artifacts:
          path: .tmp/website/sunpy.org/_build/html
  sunpy:
    resource_class: large
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: *apt-install
      - run: *tox
      # Needed to install mplcairo
      - run: sudo apt install libcairo2-dev pkg-config
      # the large resource_class has 4 CPUs but auto detection does not work
      - run: python -m tox -e sunpy_docs -- -j 8
      # Remove some parts of the build to speed up upload
      - run: rm -r .tmp/sunpy_docs/sunpy/docs/_build/html/.doctrees
      - run: rm -r .tmp/sunpy_docs/sunpy/docs/_build/html/_downloads
      - run: rm -r .tmp/sunpy_docs/sunpy/docs/_build/html/_sources
      - store_artifacts:
          path: .tmp/sunpy_docs/sunpy/docs/_build/html
  css_linting:
    resource_class: small
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: sudo npm install -g stylelint
      - run: sudo npm install stylelint-config-recommended
      - run: sudo stylelint "**/*.{css,scss,sass}"
workflows:
  version: 2
  tests:
    jobs:
      - css_linting
      - sunpy
      - website
